name: S3 Upload

on: push

jobs:
  upload:
    name: Use this action for check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.7              # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64                # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          enable-pep582: false             # Enable PEP 582 package loading globally
          allow-python-prereleases: false  # Allow prerelease versions of Python to be installed. For example if only 3.12-dev is available, 3.12 will fallback to 3.12-dev
      - name: Build wheel
        run: |
          cd etl_implementations
          pdm build                   # Then you can use pdm in the following steps.
      - name: Use this action
        uses: ./
        id: upload
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          aws-bucket: ${{ secrets.AWS_BUCKET}}
          file-path: ./README.md
          # destination-dir:
          # bucket-root:
          output-file-url: true
          # content-type:
          output-qr-url: true
          # qr-width:
          # public:
          # expire:
      - name: Show result
        if: always()
        run: |
          echo '${{ steps.upload.outputs.result }}'
          echo '${{ steps.upload.outputs.file-url }}'
          echo '${{ steps.upload.outputs.qr-url }}'
